api_platform:
    title: 'Limehome API'
    description: 'This is a challenge task with topic of booking your suite at Limehome!'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 100
    defaults:
        pagination_items_per_page: 10
